language: java
jdk:
  - openjdk11

branches:
  only:
    - master

# Mysql
services:
  - mysql

# Travis CI server Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_install:
  - chmod +x gradlew
  - mysql -e 'CREATE DATABASE localtest'

before_deploy:
  - zip -r webservice *
  - mkdir -p deploy
  - mv webservice.zip deploy/webservice.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: webservice-deploy
    region: ap-northeast-2
    skip_cleanup: true
    acl: public_read
    local_dir: deploy
    wait-until-deployed: true
    on:
      repo: ChadJung/Portfolio
      branch: master


# Notify after CI is completed
notifications:
  email:
    recipients:
      - jungsj11@gmail.com