spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/localtest?validationQuery="select 1"
    username: root
    password:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate.format-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    show-sql: true

  profiles:
    active: local
    group:
      local: localtest, common
      prod: real, common
      dev: localtest, common

management:
  endpoints:
    web:
      exposure:
        include: *
---

spring.config.activate.on-profile: common
spring:
  datasource:
    username: root
    password:
  jpa:
    generate-ddl: true
    defer-datasource-initialization: true

---

spring.config.activate.on-profile: localtest
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/localtest?validationQuery="select 1"
  sql:
    init:
      platform: mysql
      data-locations: classpath:data-mysql.sql

---

spring.config.activate.on-profile: real
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/website?validationQuery="select 1"

---

project:
  name: JunWebsite
  version: 0.0.0
  state: Development
