spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate.format-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    show-sql: true

  profiles:
    group:
      "local": "localtest, common"

---

spring:
  profiles:
    group:
      "dev": "localtest, common"

---

spring:
  profiles:
    group:
      "prod": "website, common"

---

spring:
  config:
    activate:
      on-profile: "local"
  datasource:
    url: jdbc:mysql://localhost:3306/localtest?validationQuery="select 1"
    username: root
    password:
  jpa:
    generate-ddl: true
    defer-datasource-initialization: true
  sql:
    init:
      platform: mysql
      data-locations: classpath:data-mysql.sql

---

spring:
  config:
    activate:
      on-profile: "dev"
  datasource:
    url: jdbc:mysql://localhost:3306/localtest?validationQuery="select 1"
    username: root
    password:

---

spring:
  config:
    activate:
      on-profile: "prod"
  datasource:
    url: jdbc:mysql://localhost:3306/website?validationQuery="select 1"
    username: root
    password:

---
project:
  name: JunWebsite
  version: 0.0.0
  state: Development
