spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

  jpa:
    properties:
      hibernate.format-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    show-sql: true
    defer-datasource-initialization: true

  profiles:
    active: local
    group:
      local: localtest, common, init
      prod: real, common
      dev: localtest, common
      set1: set1, real
      set2: set2, real

---

spring.config.activate.on-profile: common
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
jpa:
  hibernate:
    ddl-auto: create
    generate-ddl: true

---

spring.config.activate.on-profile: localtest
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/localtest?validationQuery="select 1"
  sql:
    init:
      platform: mysql
      data-locations: classpath:data-mysql.sql

---

spring.config.activate.on-profile: real
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/website?validationQuery="select 1"
    driver-class-name: com.mysql.cj.jdbc.Driver

---

spring.config.activate.on-profile: set1
server.port: 8081

---

spring.config.activate.on-profile: set2
server.port: 8082

---

spring.config.activate.on-profile: init
spring:
  sql:
    init:
      platform: mysql
      data-locations: classpath:data-mysql.sql

---

project:
  name: JunWebsite
  version: 0.0.0
  state: Development
